### PR TITLE
Add types.d.ts

### LINKED ISSUE #1: TypeScript type definitions
Need to add types for better DX in TypeScript

### PR DESCRIPTION
**Pull request by 2bigO**
Closes #1

### CODE REVIEW

**Comment by 2bigO** [comment]
@mikeal appreciate if you can take a look.

**Comment by mikeal** [comment]
looks like upgrading to this multiformats versions breaks things a bit, should be an easy fix though, some of the export names just changed a bit.

i’d delete your local package-lock.json and node_modules and re-run `npm install`, then you should see these test failures locally and be able to adjust the PR

**Comment by 2bigO** [comment]
Perfect, thanks @mikeal! Exactly, export names don't agree with these types ATM.

**Comment by 2bigO** [comment]
I'll fix this in a couple of days and push a commit 😉

**Comment by lidel** [comment]
@keyvan-m-sadeghi do you plan to work on this, or should we close it for now?

**Comment by 2bigO** [comment]
@lidel haven't found the time to work on it yet, we can close this PR, I'll submit a new one when I had everything ready.

**Pull request closed without merging**
